csql -u dba testdb -c "create table api04a (a int)"
csql -u dba testdb -c "create table api04b (a int)"
csql -u dba testdb -c "create table api04c (a int)"

csql -u dba testdb -c "insert into api04a values (1)"
csql -u dba testdb -c "insert into api04a values (2)"
csql -u dba testdb -c "insert into api04a values (3)"
csql -u dba testdb -c "insert into api04b values (11)"
csql -u dba testdb -c "insert into api04b values (22)"
csql -u dba testdb -c "insert into api04b values (33)"
csql -u dba testdb -c "insert into api04c values (111)"
csql -u dba testdb -c "insert into api04c values (222)"
csql -u dba testdb -c "insert into api04c values (333)"
